[template]
src = "production.tmpl"
dest = "public/env-config.js"
keys = [
  "/configuration/map/center",
  "/configuration/map/zoom",
  "/configuration/base/maps",
  "/configuration/default/terrain/provider/url"
]
