[template]
src = "production.tmpl"
dest = "public/env-config.js"
keys = [
  "/configuration/public/url",
  "/configuration/map/center",
  "/configuration/map/zoom",
  "/configuration/base/maps",
  "/configuration/default/terrain/provider/url",
  "/configuration/apps",
  "/configuration/csw/3d/url",
  "/configuration/access/token/attribute/name",
  "/configuration/access/token/injection/type",
  "/configuration/should/show/precision/disclaimer",
  "/configuration/image/tag",
]
