{{- if .Values.tools.enabled -}}
{{- $environment := include "app.environment" . -}}
{{- $cloudProviderDockerRegistryUrl := include "app.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "app.cloudProviderImagePullSecretName" . -}}
{{- $cloudProviderImagePullPolicy := include "app.cloudProviderImagePullPolicy" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}-tools
  labels:
    app: {{ template "app.name" . }}
    component: tools-deployment
    environment: {{ $environment }}
    release: {{ .Release.Name }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.tools.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-tools
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-tools
    spec:
      {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-tools
          image: {{ $cloudProviderDockerRegistryUrl }}/{{ .Values.tools.image }}:{{ .Values.tools.imageTag }}
          imagePullPolicy: {{ $cloudProviderImagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            # runAsUser: 0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /env-config.js
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /env-config.js
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
          {{- if .Values.tools.resources.enabled }}
          resources:
            limits:
              cpu: {{ .Values.tools.resources.limits.cpu }}
              memory: {{ .Values.tools.resources.limits.memory }}
            requests:
              cpu: {{ .Values.tools.resources.requests.cpu }}
              memory: {{ .Values.tools.resources.requests.memory }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "app.fullname" . }}-tools-configmap
          {{- if .Values.sso.enabled }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          {{- end }}
        {{- if .Values.sso.enabled }}
        volume:
          - name: nginx-config
            configMap:
              name: {{ template "app.fullname" . }}-tools-configmap
              items:
                - key: default.conf
                  path: default.conf
        {{- end }}
{{- end }}
