{{- if .Values.mcTools.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mc-tools.fullname" . }}
  labels:
    app: {{ template "mc-tools.name" . }}
    component: mc-tools-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
  annotations:
    collectord.io/index: {{ quote .Values.splunkIndex }}    
spec:
  replicas: {{ .Values.mcTools.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "mc-tools.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "mc-tools.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.pullSecretName }}
      containers:    
        - name: {{ .Chart.Name }}
          image: "{{ .Values.mcTools.image }}:{{ .Values.mcTools.imageTag}}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ template "mc-tools.fullname" . }}-configmap
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          {{- if .Values.mcTools.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.mcTools.resources.requests.memory }}
              cpu: {{ .Values.mcTools.resources.requests.cpu }}
            limits:
              memory: {{ .Values.mcTools.resources.limits.memory }}
              cpu: {{ .Values.mcTools.resources.limits.cpu }}
          {{- end }}
{{- end }}
