{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "mc-web-tools.fullname" . }}-route
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
spec:
  path:  {{ .Values.route.path }}
  to:
    kind: Service
    name: {{ template "mc-web-tools.fullname" . }}
  port:
    targetPort: http
  {{- if .Values.route.tls }}
  tls:
    termination: edge
  {{- end -}}
{{- end -}}
