{{- if .Values.s3Secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-s3-secret
type: Opaque
stringData:
  accessKeyId: {{ quote .Values.s3Secret.accessKeyId }}
  secretAccessKey: {{ quote .Values.s3Secret.secretAccessKey }}
{{- end }}
